### ISSUE TITLE
Thumbnails might be too big for the layout

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#9]
Here's my weekly bug report. :octocat: 

Since the new Molotov theme, I believe channel thumbnails are showing bigger than they should, or it's just the "Chaînes" header that is too big or to low in Y, and it makes it hard to select (and see) the first row of channels in the "Chaînes" view:

![](https://reho.st/https://0x0.st/sV4s.png)

I don't have Molotov at hand here to check, but I used it a couple days ago on someone else's computer and I think there was no such issue. 

Also, aren't covers for shows (in the main view) a bit bigger than in Molotov application too? I suppose it might be because Viatcheslav is displaying the webview of molotov.tv, but maybe there would be a workaround to scale everything down a bit so that it looks a bit more like the Molotov application.

**Comment by Kabouik** [comment]
I'm wrong on the thumbnail and cover size, it just seems that the left headers are too low in Viatcheslav (right) compared to Molotov (left):

![](https://reho.st/0x0.st/sVE_.png)

I'm glad we're avoiding the ads banner with Viatcheslav though!

**Comment by Rudloff** [comment]
I think the ad-blocking is a side effect of https://github.com/Rudloff/viatcheslav/commit/e55ec85b88d1d79d2c61dc0a91a4b06153bd9e9b (I whitelisted authorized domains and ads are served from a separate domain).

As for the "Chaînes" issue, it happens because the searchbar is not there and it messes up the layout, so I had to move the text block manually: 7f32a57
This change might easily break with a future Molotov update though.
